[package]
name = "gitcheck"
version = "0.0.1"
authors = ["Maxim Zhukov <mussitantesmortem@gmail.com>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
clap = "3.0.0-beta.1"
crossbeam-channel = "0.4.3"
crossbeam-utils = "0.7.2"
flexi_logger = "0.15"
git2 = "0.13"
log = "0.4"
num_cpus = "1.13.0"
regex = "1.3.9"
